package com.restaurant.system.menu.addon;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.restaurant.system.common.exception.BusinessException;
import com.restaurant.system.menu.service.MenuRevisionService;
import com.restaurant.system.printing.rules.PrintingDisplayRuleContext;
import com.restaurant.system.printing.rules.PrintingDisplayRuleService;
import jakarta.persistence.EntityManager;
import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.TransactionTemplate;

/** Real JDBC transactions/locks, including failure after the first write and parallel requests. */
class StoreAddonServiceIntegrationTest {
    @Configuration
    @EnableTransactionManagement(proxyTargetClass = true)
    static class Transactions {}

    private AnnotationConfigApplicationContext context;
    private JdbcTemplate jdbc;
    private StoreAddonService service;
    private PrintingDisplayRuleService printing;
    private PlatformTransactionManager transactionManager;

    @BeforeEach
    void setup() {
        var dataSource = new DriverManagerDataSource("jdbc:h2:mem:addon_" + UUID.randomUUID()
            + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000", "sa", "");
        jdbc = new JdbcTemplate(dataSource);
        transactionManager = new DataSourceTransactionManager(dataSource);
        jdbc.execute("create table organizations(id bigint primary key)");
        jdbc.execute("create table stores(id bigint primary key,organization_id bigint not null references organizations(id),menu_revision bigint default 1,unique(id,organization_id))");
        jdbc.execute("create table menu_items(id bigint primary key,store_id bigint not null references stores(id),unique(id,store_id))");
        jdbc.execute("""
            create table organization_addon_definitions(id bigint generated by default as identity primary key,
            organization_id bigint not null references organizations(id),code varchar(255) not null,
            created_at timestamp,updated_at timestamp,unique(organization_id,code),unique(id,organization_id))
            """);
        jdbc.execute("""
            create table store_addons(id bigint generated by default as identity primary key,store_id bigint not null,
            organization_id bigint not null,organization_addon_definition_id bigint not null,name_zh varchar(255),
            name_en varchar(255),price numeric(38,2),active boolean,created_at timestamp,updated_at timestamp,
            unique(store_id,organization_addon_definition_id),unique(id,store_id),
            foreign key(store_id,organization_id) references stores(id,organization_id),
            foreign key(organization_addon_definition_id,organization_id) references organization_addon_definitions(id,organization_id))
            """);
        jdbc.execute("""
            create table menu_item_options(id bigint generated by default as identity primary key,menu_item_id bigint,
            option_type varchar(50),option_code varchar(255),option_group varchar(50),name_zh varchar(255),name_en varchar(255),
            price_delta numeric(38,2),is_active boolean,store_addon_id bigint,store_addon_store_id bigint,addon_eligible boolean,
            parent_option_id bigint,sort_order int,created_at timestamp,updated_at timestamp,
            foreign key(menu_item_id,store_addon_store_id) references menu_items(id,store_id),
            foreign key(store_addon_id,store_addon_store_id) references store_addons(id,store_id))
            """);
        jdbc.execute("create table order_item_options(id bigint primary key,menu_item_option_id bigint,name_zh varchar(255),price_delta numeric(38,2))");
        jdbc.update("insert into organizations values (1),(2)");
        jdbc.update("insert into stores(id,organization_id) values (1,1),(2,1),(3,2)");
        jdbc.update("insert into menu_items values (10,1),(11,1),(20,2),(30,3)");
        MenuRevisionService revisions = mock(MenuRevisionService.class);
        when(revisions.lockStoresInOrder(any())).thenAnswer(invocation -> {
            for (Long id : (List<Long>) invocation.getArgument(0)) {
                assertThat(jdbc.queryForList("select id from stores where id=? for update", id)).hasSize(1);
            }
            return List.of();
        });
        doAnswer(invocation -> { jdbc.update("update stores set menu_revision=menu_revision+1 where id=?", (Long) invocation.getArgument(0)); return null; })
            .when(revisions).incrementRevision(anyLong());
        printing = mock(PrintingDisplayRuleService.class);
        when(printing.activeContext(anyLong())).thenReturn(PrintingDisplayRuleContext.defaultContext());
        context = new AnnotationConfigApplicationContext();
        context.register(Transactions.class);
        context.registerBean(PlatformTransactionManager.class, () -> transactionManager);
        context.registerBean(StoreAddonService.class, () -> new StoreAddonService(jdbc, revisions, printing, mock(EntityManager.class)));
        context.refresh();
        service = context.getBean(StoreAddonService.class);
    }

    @AfterEach void close() { context.close(); }

    @Test
    void reconciliationIsDeterministicReadOnlyOnGetAndDryRunAndIdempotent() {
        option(10, "beef", "牛肉", "Beef", "2.00", true);
        option(11, "beef", "牛肉", "Beef", "2.00", false);
        // A duplicate current row retains its own transport/database identity.
        option(10, "beef", "牛肉", "Beef", "2.00", true);
        option(10, "bad-code", "无效", "Invalid", "1.00", true);
        option(10, null, "无代码", null, "1.00", true);
        option(10, "conflict", "甲", "A", "1.00", true);
        option(11, "conflict", "乙", "B", "2.00", true);
        assertThat(service.getAddons(1L).conflicts()).hasSize(3);
        assertThat(count("store_addons")).isZero();
        var dry = service.reconcile(1L, true);
        assertThat(dry.linked_groups()).isEqualTo(1);
        assertThat(dry.linked_options()).isEqualTo(3);
        assertThat(dry.conflicts()).extracting(StoreAddonService.Conflict::code).containsExactly(null, "bad-code", "conflict");
        assertThat(count("store_addons")).isZero();
        assertThat(revision(1)).isEqualTo(1);
        var applied = service.reconcile(1L, false);
        assertThat(applied.conflicts()).isEqualTo(dry.conflicts());
        assertThat(count("menu_item_options")).isEqualTo(7);
        assertThat(jdbc.queryForList("select addon_eligible from menu_item_options where store_addon_id is not null", Boolean.class))
            .containsExactly(true, false, true);
        assertThat(service.getAddons(1L).addons()).singleElement().satisfies(a -> assertThat(a.active()).isTrue());
        assertThat(service.reconcile(1L, false).linked_options()).isZero();
        assertThat(revision(1)).isEqualTo(2);
    }

    @Test
    void sameItemActiveDifferenceRemainsAnUnmodifiedConflictAcrossDryRunApplyAndReplay() {
        long first = option(10, "beef", "牛肉", "Beef", "2.00", true);
        long second = option(10, "beef", "牛肉", "Beef", "2.00", false);
        long otherItem = option(11, "beef", "牛肉", "Beef", "2.00", true);
        assertUnlinkedRelationshipConflictPreserved(first, second, otherItem);
    }

    @Test
    void sameItemParentDifferenceRemainsAnUnmodifiedConflictAcrossDryRunApplyAndReplay() {
        long first = option(10, "beef", "牛肉", "Beef", "2.00", true);
        long second = option(10, "beef", "牛肉", "Beef", "2.00", true);
        jdbc.update("update menu_item_options set parent_option_id=? where id=?", first, second);
        assertUnlinkedRelationshipConflictPreserved(first, second);
    }

    @Test
    void sameItemEqualParentAndEligibilityDuplicatesPreserveBothIds() {
        long first = option(10, "beef", "牛肉", "Beef", "2.00", true);
        long second = option(10, "beef", "牛肉", "Beef", "2.00", true);
        long parent = option(10, "parent", "父选项", "Parent", "0.00", true);
        jdbc.update("update menu_item_options set option_group='REMOVE',option_type='remove' where id=?", parent);
        jdbc.update("update menu_item_options set parent_option_id=? where id in (?,?)", parent, first, second);
        var report = service.reconcile(1L, false);
        assertThat(report.conflicts()).isEmpty();
        assertThat(report.linked_options()).isEqualTo(2);
        assertThat(jdbc.queryForList("select id from menu_item_options where store_addon_id is not null order by id", Long.class))
            .containsExactly(first, second);
        assertThat(jdbc.queryForList("select parent_option_id from menu_item_options where store_addon_id is not null", Long.class))
            .containsExactly(parent, parent);
        assertThat(service.reconcile(1L, false).linked_options()).isZero();
    }

    @Test
    void linkedEligibilityDifferenceIsStillAmbiguousWhenCatalogInactiveMasksActiveDifference() {
        var addon = service.create(request(1, "beef", "牛肉", "Beef", "2.00", false));
        long first = option(10, "beef", "牛肉", "Beef", "2.00", false);
        long second = option(10, "beef", "牛肉", "Beef", "2.00", false);
        jdbc.update("update menu_item_options set store_addon_id=?,store_addon_store_id=1,addon_eligible=true where id=?", addon.id(), first);
        jdbc.update("update menu_item_options set store_addon_id=?,store_addon_store_id=1,addon_eligible=false where id=?", addon.id(), second);
        var before = jdbc.queryForList("select * from menu_item_options order by id");
        var dry = service.reconcile(1L, true);
        assertThat(dry.conflicts()).singleElement().satisfies(c -> assertThat(c.reason()).isEqualTo("ADDON_RELATIONSHIP_CONFLICT"));
        assertThat(service.reconcile(1L, false).conflicts()).isEqualTo(dry.conflicts());
        assertThat(service.reconcile(1L, false).conflicts()).isEqualTo(dry.conflicts());
        assertThatThrownBy(() -> service.setEligibility(10L, addon.id(), true)).hasMessageContaining("ADDON_RELATIONSHIP_CONFLICT");
        assertThat(jdbc.queryForList("select * from menu_item_options order by id")).isEqualTo(before);
        assertThat(revision(1)).isEqualTo(2);
    }

    private void assertUnlinkedRelationshipConflictPreserved(Long... optionIds) {
        var before = jdbc.queryForList("select * from menu_item_options order by id");
        var conflicts = service.getAddons(1L).conflicts();
        assertThat(conflicts).singleElement().satisfies(c -> {
            assertThat(c.reason()).isEqualTo("ADDON_RELATIONSHIP_CONFLICT");
            assertThat(c.option_ids()).containsExactly(optionIds);
        });
        for (boolean dryRun : List.of(true, false, false)) {
            var result = service.reconcile(1L, dryRun);
            assertThat(result.conflicts()).isEqualTo(conflicts);
            assertThat(result.linked_groups()).isZero();
            assertThat(result.linked_options()).isZero();
            assertThat(jdbc.queryForList("select * from menu_item_options order by id")).isEqualTo(before);
        }
        assertThat(count("store_addons")).isZero();
        assertThat(count("organization_addon_definitions")).isZero();
        assertThat(revision(1)).isEqualTo(1);
    }

    @Test
    void catalogRenameAndRepricePropagateAllRowsAndEligibilitySurvivesActiveCycle() {
        long first = option(10, "beef", "牛肉", "Beef", "2.00", true);
        option(11, "beef", "牛肉", "Beef", "2.00", false);
        jdbc.update("insert into order_item_options values (100,?,'牛肉',2.00)", first);
        service.reconcile(1L, false);
        var addon = service.getAddons(1L).addons().get(0);
        service.update(addon.id(), request(1, "beef", "精选牛肉", "Premium beef", "3.25", false));
        assertThat(jdbc.queryForList("select is_active from menu_item_options", Boolean.class)).containsOnly(false);
        assertThat(jdbc.queryForList("select name_zh from menu_item_options", String.class)).containsOnly("精选牛肉");
        assertThat(jdbc.queryForList("select price_delta from menu_item_options", BigDecimal.class)).containsOnly(new BigDecimal("3.25"));
        assertThat(service.getItemAddons(10L).get(0).enabled()).isTrue();
        assertThat(service.getItemAddons(11L).get(0).enabled()).isFalse();
        service.update(addon.id(), request(1, null, "精选牛肉", "Premium beef", "3.25", true));
        assertThat(jdbc.queryForList("select is_active from menu_item_options order by id", Boolean.class)).containsExactly(true, false);
        assertThat(jdbc.queryForMap("select name_zh,price_delta from order_item_options where id=100"))
            .containsEntry("name_zh", "牛肉").containsEntry("price_delta", new BigDecimal("2.00"));
        assertThat(jdbc.queryForObject("select id from menu_item_options where menu_item_id=10", Long.class)).isEqualTo(first);
    }

    @Test
    void createNormalizesCodeRejectsMutationAndKeepsStoresAndOrganizationsIndependent() {
        var a = service.create(request(1, "  Beef-Tendon  ", "牛筋", "Tendon", "3.00", true));
        var b = service.create(request(2, "beef_tendon", "加牛筋", "More tendon", "4.00", false));
        service.create(request(3, "beef_tendon", "牛筋", "Tendon", "5.00", true));
        assertThat(a.code()).isEqualTo("beef_tendon");
        assertThat(count("organization_addon_definitions")).isEqualTo(2);
        assertThatThrownBy(() -> service.update(a.id(), request(1, "different", "牛筋", "Tendon", "3.00", true)))
            .isInstanceOf(BusinessException.class).hasMessage("ADDON_CODE_IMMUTABLE");
        assertThatThrownBy(() -> service.setEligibility(20L, a.id(), true)).hasMessage("ADDON_STORE_MISMATCH");
        assertThatThrownBy(() -> service.setEligibility(30L, a.id(), true)).hasMessage("ADDON_STORE_MISMATCH");
        service.update(a.id(), request(1, null, "新名称", "Renamed", "6.00", true));
        assertThat(service.getAddons(2L).addons().get(0)).isEqualTo(b);
        assertThat(revision(2)).isEqualTo(2);
    }

    @Test
    void togglingEligibilityCreatesOneStableOptionAndDoesNotEnableInactiveCatalog() {
        var addon = service.create(request(1, "tendon", "牛筋", "Tendon", "3.00", false));
        service.setEligibility(10L, addon.id(), true);
        long id = jdbc.queryForObject("select id from menu_item_options", Long.class);
        assertThat(service.getItemAddons(10L).get(0).enabled()).isTrue();
        assertThat(jdbc.queryForObject("select is_active from menu_item_options", Boolean.class)).isFalse();
        service.setEligibility(10L, addon.id(), false);
        service.setEligibility(10L, addon.id(), true);
        assertThat(count("menu_item_options")).isEqualTo(1);
        assertThat(jdbc.queryForObject("select id from menu_item_options", Long.class)).isEqualTo(id);
    }

    @Test
    void printingCoverageUsesAddonCodeOnlyAndNeverComboDictionary() {
        when(printing.activeContext(1L)).thenReturn(new PrintingDisplayRuleContext(1L, 1, "x",
            com.restaurant.system.owner.profile.StoreProfileCanonicalJson.parse("""
                {"dictionaries":{"MODIFIER_ADD":[["fried_egg","+蛋"]],
                  "COMBO_EGG":[{"match_codes":["combo_fried_egg"],"outputs":{"HOT_KITCHEN":"煎蛋"}}]}}
                """)));
        var addon = service.create(request(1, "fried_egg", "煎蛋", "Fried egg", "1.00", true));
        var comboNamed = service.create(request(1, "combo_fried_egg", "煎蛋", "Fried egg", "1.00", true));
        assertThat(addon.printing_configured()).isTrue();
        assertThat(comboNamed.printing_configured()).isFalse();
        service.setEligibility(10L, comboNamed.id(), true);
        assertThat(service.getItemAddons(10L)).filteredOn(a -> a.id().equals(comboNamed.id())).singleElement()
            .satisfies(a -> assertThat(a.enabled()).isTrue());
    }

    @Test
    void legacyConflictCannotBeBypassedByCreateOrEligibilityAndComboRowsStaySeparate() {
        option(10, "beef", "甲", "A", "1.00", true);
        option(11, "beef", "乙", "B", "2.00", true);
        assertThatThrownBy(() -> service.create(request(1, "beef", "甲", "A", "1.00", true))).hasMessageContaining("ADDON_LEGACY_CONFLICT");
        long combo = option(10, "combo_fried_egg", "煎蛋", "Fried egg", "0.00", true);
        jdbc.update("update menu_item_options set option_group='COMBO_EGG' where id=?", combo);
        assertThat(service.reconcile(1L, false).linked_options()).isZero();
        assertThat(count("store_addons")).isZero();
        var addon = service.create(request(1, "tendon", "牛筋", "Tendon", "3.00", true));
        option(10, "tendon", "旧牛筋", "Legacy", "4.00", true);
        assertThatThrownBy(() -> service.setEligibility(10L, addon.id(), true)).hasMessageContaining("ADDON_LEGACY_CONFLICT");
        assertThat(service.reconcile(1L, false).conflicts()).extracting(StoreAddonService.Conflict::reason)
            .contains("ADDON_CATALOG_VALUES_CONFLICT");
    }

    @Test
    void reconciliationRollsBackEntireTransactionOnLateLinkFailure() {
        option(10, "a_beef", "牛肉", "Beef", "2.00", true);
        long fail = option(11, "b_tendon", "牛筋", "Tendon", "3.00", true);
        jdbc.execute("alter table menu_item_options add constraint fail_link check(id<>" + fail + " or store_addon_id is null)");
        assertThatThrownBy(() -> service.reconcile(1L, false)).isInstanceOf(RuntimeException.class);
        assertThat(count("store_addons")).isZero();
        assertThat(count("organization_addon_definitions")).isZero();
        assertThat(jdbc.queryForObject("select count(*) from menu_item_options where store_addon_id is not null", Long.class)).isZero();
        assertThat(revision(1)).isEqualTo(1);
    }

    @Test
    void failedPropagationRollsBackCatalogAndRevision() {
        option(10, "beef", "牛肉", "Beef", "2.00", true);
        service.reconcile(1L, false);
        var addon = service.getAddons(1L).addons().get(0);
        jdbc.execute("alter table menu_item_options add constraint fail_price check(price_delta<3)");
        assertThatThrownBy(() -> service.update(addon.id(), request(1, null, "变更", "Changed", "4.00", false))).isInstanceOf(RuntimeException.class);
        assertThat(service.getAddons(1L).addons().get(0)).isEqualTo(addon);
        assertThat(revision(1)).isEqualTo(2);
    }

    @Test
    void duplicateConcurrentCreationAndEligibilityAreSerialized() throws Exception {
        var executor = Executors.newFixedThreadPool(2);
        try {
            var start = new CountDownLatch(1);
            var futures = java.util.stream.IntStream.range(0, 2).mapToObj(n -> executor.submit(() -> {
                start.await();
                try { service.create(request(1, "beef", "牛肉", "Beef", "2.00", true)); return "created"; }
                catch (BusinessException e) { return e.getMessage(); }
            })).toList();
            start.countDown();
            List<String> results = List.of(futures.get(0).get(10, TimeUnit.SECONDS), futures.get(1).get(10, TimeUnit.SECONDS));
            assertThat(results).contains("created").anySatisfy(r -> assertThat(r).startsWith("ADDON_CODE_EXISTS"));
            assertThat(count("store_addons")).isEqualTo(1);
            Long id = service.getAddons(1L).addons().get(0).id();
            var a = executor.submit(() -> service.setEligibility(10L, id, true));
            var b = executor.submit(() -> service.setEligibility(10L, id, true));
            a.get(10, TimeUnit.SECONDS); b.get(10, TimeUnit.SECONDS);
            assertThat(count("menu_item_options")).isEqualTo(1);
        } finally { executor.shutdownNow(); }
    }

    @Test
    void twoStoresConcurrentlyShareOneOrganizationDefinition() throws Exception {
        var executor = Executors.newFixedThreadPool(2);
        try {
            var start = new CountDownLatch(1);
            var a = executor.submit(() -> { start.await(); return service.create(request(1, "beef", "牛肉", "Beef", "2.00", true)); });
            var b = executor.submit(() -> { start.await(); return service.create(request(2, "beef", "牛肉", "Beef", "4.00", true)); });
            start.countDown(); a.get(10, TimeUnit.SECONDS); b.get(10, TimeUnit.SECONDS);
            assertThat(count("organization_addon_definitions")).isEqualTo(1);
            assertThat(count("store_addons")).isEqualTo(2);
        } finally { executor.shutdownNow(); }
    }

    @Test
    void databaseRejectsCrossStoreAndOrganizationLinks() {
        var addon = service.create(request(1, "beef", "牛肉", "Beef", "2.00", true));
        assertThatThrownBy(() -> jdbc.update("insert into store_addons(store_id,organization_id,organization_addon_definition_id) values (3,2,1)"))
            .isInstanceOf(RuntimeException.class);
        long option = option(20, "beef", "牛肉", "Beef", "2.00", true);
        assertThatThrownBy(() -> jdbc.update("update menu_item_options set store_addon_id=?,store_addon_store_id=1,addon_eligible=true where id=?", addon.id(), option))
            .isInstanceOf(RuntimeException.class);
    }

    @Test
    void itemMovedAfterControllerAuthorizationCannotReadOrMutateOtherStore() {
        var addon = service.create(request(2, "beef", "牛肉", "Beef", "2.00", true));
        long previouslyAuthorizedStore = service.storeIdForItem(10L);
        jdbc.update("update menu_items set store_id=2 where id=10");
        assertThatThrownBy(() -> service.getItemAddons(10L, previouslyAuthorizedStore)).hasMessage("ADDON_STORE_MISMATCH");
        assertThatThrownBy(() -> service.setEligibility(10L, addon.id(), true, previouslyAuthorizedStore)).hasMessage("ADDON_STORE_MISMATCH");
        assertThat(count("menu_item_options")).isZero();
        assertThat(revision(2)).isEqualTo(2);
    }

    @Test
    void reconciliationParticipatesInOuterProvisioningTransaction() {
        option(10, "beef", "牛肉", "Beef", "2.00", true);
        assertThatThrownBy(() -> new TransactionTemplate(transactionManager).execute(status -> {
            service.reconcile(1L, false);
            assertThat(count("store_addons")).isEqualTo(1);
            throw new BusinessException("PROVISIONING_LATE_FAILURE");
        })).hasMessage("PROVISIONING_LATE_FAILURE");
        assertThat(count("store_addons")).isZero();
        assertThat(revision(1)).isEqualTo(1);
    }

    private long option(long itemId, String code, String zh, String en, String price, boolean active) {
        jdbc.update("""
            insert into menu_item_options(menu_item_id,option_type,option_group,option_code,name_zh,name_en,price_delta,is_active)
            values (?,'addon','ADD_ON',?,?,?,?,?)
            """, itemId, code, zh, en, new BigDecimal(price), active);
        return jdbc.queryForObject("select max(id) from menu_item_options", Long.class);
    }

    private StoreAddonService.WriteRequest request(long store, String code, String zh, String en, String price, boolean active) {
        var request = new StoreAddonService.WriteRequest();
        request.store_id = store; request.code = code; request.name_zh = zh; request.name_en = en;
        request.price = new BigDecimal(price); request.active = active; return request;
    }
    private long count(String table) { return jdbc.queryForObject("select count(*) from " + table, Long.class); }
    private long revision(long storeId) { return jdbc.queryForObject("select menu_revision from stores where id=?", Long.class, storeId); }
}
