CREATE TABLE public.owner_store_menu_clone_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    source_store_id bigint NOT NULL,
    target_store_id bigint NOT NULL,
    idempotency_key character varying(255) NOT NULL,
    request_fingerprint character varying(64) NOT NULL,
    profile_code character varying(96) NOT NULL,
    status character varying(32) NOT NULL,
    source_menu_revision bigint,
    target_revision_before bigint,
    target_revision_after bigint,
    created_station_count integer,
    created_category_count integer,
    created_item_count integer,
    created_option_count integer,
    result_code character varying(64),
    error_code character varying(64),
    actor_user_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone,
    CONSTRAINT uq_owner_store_menu_clone_scope_key UNIQUE (
        organization_id,
        source_store_id,
        target_store_id,
        idempotency_key
    ),
    CONSTRAINT chk_owner_store_menu_clone_status CHECK (
        status IN ('PROCESSING', 'COMPLETED', 'FAILED')
    )
);

CREATE INDEX idx_owner_store_menu_clone_target_store
    ON public.owner_store_menu_clone_requests (target_store_id);
