DO $$
DECLARE
    conflict_count integer;
BEGIN
    WITH semantic_prices AS (
        SELECT
            item.store_id,
            CASE
                WHEN lower(coalesce(option_row.option_group, '')) = 'size'
                  OR lower(coalesce(option_row.option_type, '')) = 'size'
                THEN CASE
                    WHEN lower(coalesce(option_row.option_code, '')) = 'size_small'
                      OR option_row.name_zh = '小碗'
                      OR lower(coalesce(option_row.name_en, '')) = 'small'
                    THEN 'SIZE_SMALL'
                    WHEN lower(coalesce(option_row.option_code, '')) = 'size_regular'
                      OR option_row.name_zh = '中碗'
                      OR lower(coalesce(option_row.name_en, '')) = 'regular'
                    THEN 'SIZE_REGULAR'
                    WHEN lower(coalesce(option_row.option_code, '')) = 'size_large'
                      OR option_row.name_zh = '大碗'
                      OR lower(coalesce(option_row.name_en, '')) = 'large'
                    THEN 'SIZE_LARGE'
                    ELSE NULL
                END
                WHEN lower(coalesce(option_row.option_group, '')) = 'combo'
                  OR lower(coalesce(option_row.option_code, '')) = 'combo'
                  OR (
                    lower(coalesce(option_row.option_type, '')) = 'addon'
                    AND option_row.name_zh = '套餐'
                  )
                  OR (
                    lower(coalesce(option_row.option_type, '')) = 'addon'
                    AND lower(coalesce(option_row.name_en, '')) = 'combo'
                  )
                THEN 'COMBO'
                ELSE NULL
            END AS semantic_key,
            option_row.price_delta
        FROM public.menu_item_options option_row
        JOIN public.menu_items item ON item.id = option_row.menu_item_id
        WHERE option_row.is_active IS TRUE
    ),
    conflicts AS (
        SELECT store_id, semantic_key
        FROM semantic_prices
        WHERE semantic_key IS NOT NULL
        GROUP BY store_id, semantic_key
        HAVING COUNT(DISTINCT price_delta) > 1
    )
    SELECT COUNT(*) INTO conflict_count
    FROM conflicts;

    IF conflict_count > 0 THEN
        RAISE EXCEPTION 'PHASE_A0_1_PRICING_POLICY_BACKFILL_CONFLICT_WAITING_FOR_OWNER_DECISION';
    END IF;
END $$;

CREATE TABLE public.store_pricing_policies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    size_small_delta numeric(38,2) NOT NULL,
    size_regular_delta numeric(38,2) NOT NULL,
    size_large_delta numeric(38,2) NOT NULL,
    combo_delta numeric(38,2) NOT NULL,
    policy_revision bigint NOT NULL DEFAULT 1,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_store_pricing_policies_store UNIQUE (store_id),
    CONSTRAINT fk_store_pricing_policies_store
        FOREIGN KEY (store_id) REFERENCES public.stores(id)
);

CREATE INDEX idx_store_pricing_policies_store
    ON public.store_pricing_policies (store_id);

WITH semantic_prices AS (
    SELECT
        item.store_id,
        CASE
            WHEN lower(coalesce(option_row.option_group, '')) = 'size'
              OR lower(coalesce(option_row.option_type, '')) = 'size'
            THEN CASE
                WHEN lower(coalesce(option_row.option_code, '')) = 'size_small'
                  OR option_row.name_zh = '小碗'
                  OR lower(coalesce(option_row.name_en, '')) = 'small'
                THEN 'SIZE_SMALL'
                WHEN lower(coalesce(option_row.option_code, '')) = 'size_regular'
                  OR option_row.name_zh = '中碗'
                  OR lower(coalesce(option_row.name_en, '')) = 'regular'
                THEN 'SIZE_REGULAR'
                WHEN lower(coalesce(option_row.option_code, '')) = 'size_large'
                  OR option_row.name_zh = '大碗'
                  OR lower(coalesce(option_row.name_en, '')) = 'large'
                THEN 'SIZE_LARGE'
                ELSE NULL
            END
            WHEN lower(coalesce(option_row.option_group, '')) = 'combo'
              OR lower(coalesce(option_row.option_code, '')) = 'combo'
              OR (
                lower(coalesce(option_row.option_type, '')) = 'addon'
                AND option_row.name_zh = '套餐'
              )
              OR (
                lower(coalesce(option_row.option_type, '')) = 'addon'
                AND lower(coalesce(option_row.name_en, '')) = 'combo'
              )
            THEN 'COMBO'
            ELSE NULL
        END AS semantic_key,
        option_row.price_delta
    FROM public.menu_item_options option_row
    JOIN public.menu_items item ON item.id = option_row.menu_item_id
    WHERE option_row.is_active IS TRUE
),
semantic_policy AS (
    SELECT
        store_id,
        MAX(price_delta) FILTER (WHERE semantic_key = 'SIZE_SMALL') AS size_small_delta,
        MAX(price_delta) FILTER (WHERE semantic_key = 'SIZE_REGULAR') AS size_regular_delta,
        MAX(price_delta) FILTER (WHERE semantic_key = 'SIZE_LARGE') AS size_large_delta,
        MAX(price_delta) FILTER (WHERE semantic_key = 'COMBO') AS combo_delta
    FROM semantic_prices
    WHERE semantic_key IS NOT NULL
    GROUP BY store_id
)
INSERT INTO public.store_pricing_policies (
    store_id,
    size_small_delta,
    size_regular_delta,
    size_large_delta,
    combo_delta,
    policy_revision,
    created_at,
    updated_at
)
SELECT
    store_row.id,
    COALESCE(semantic_policy.size_small_delta, -2.00),
    COALESCE(semantic_policy.size_regular_delta, 0.00),
    COALESCE(semantic_policy.size_large_delta, 2.00),
    COALESCE(semantic_policy.combo_delta, 5.00),
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM public.stores store_row
LEFT JOIN semantic_policy ON semantic_policy.store_id = store_row.id;
