CREATE TABLE public.store_combo_components (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    component_group character varying(64) NOT NULL,
    component_code character varying(128) NOT NULL,
    name_zh character varying(255) NOT NULL,
    name_en character varying(255) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    display_order integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_store_combo_components_store_group_code
        UNIQUE (store_id, component_group, component_code),
    CONSTRAINT fk_store_combo_components_store
        FOREIGN KEY (store_id) REFERENCES public.stores(id),
    CONSTRAINT chk_store_combo_components_group
        CHECK (component_group IN ('COMBO_EGG', 'COMBO_SIDE')),
    CONSTRAINT chk_store_combo_components_code
        CHECK (
            (component_group = 'COMBO_EGG'
                AND component_code IN ('combo_tea_egg', 'combo_fried_egg'))
            OR
            (component_group = 'COMBO_SIDE'
                AND component_code IN (
                    'combo_edamame',
                    'combo_shredded_potato',
                    'combo_cucumber_salad'
                ))
        )
);

CREATE INDEX idx_store_combo_components_store
    ON public.store_combo_components (store_id);

CREATE INDEX idx_store_combo_components_store_group_order
    ON public.store_combo_components (store_id, component_group, display_order);

WITH canonical_components AS (
    SELECT *
    FROM (VALUES
        ('COMBO_EGG', 'combo_tea_egg', '卤蛋', 'Tea Egg', 10),
        ('COMBO_EGG', 'combo_fried_egg', '煎蛋', 'Fried Egg', 20),
        ('COMBO_SIDE', 'combo_edamame', '毛豆', 'Edamame', 10),
        ('COMBO_SIDE', 'combo_shredded_potato', '土豆丝', 'Shredded Potato', 20),
        ('COMBO_SIDE', 'combo_cucumber_salad', '拌黄瓜', 'Cucumber Salad', 30)
    ) AS component(component_group, component_code, name_zh, name_en, display_order)
),
existing_component_semantics AS (
    SELECT DISTINCT
        item.store_id,
        CASE
            WHEN upper(coalesce(option_row.option_group, '')) = 'COMBO_EGG'
              OR lower(coalesce(option_row.option_code, '')) IN ('combo_tea_egg', 'combo_fried_egg')
              OR option_row.name_zh IN ('套餐卤蛋', '卤蛋')
            THEN 'COMBO_EGG'
            WHEN upper(coalesce(option_row.option_group, '')) = 'COMBO_SIDE'
              OR lower(coalesce(option_row.option_code, '')) IN (
                    'combo_edamame',
                    'combo_shredded_potato',
                    'combo_cucumber_salad'
                )
              OR option_row.name_zh IN ('套餐毛豆', '套餐土豆丝', '套餐拌黄瓜')
            THEN 'COMBO_SIDE'
            ELSE NULL
        END AS component_group,
        CASE
            WHEN lower(coalesce(option_row.option_code, '')) = 'combo_tea_egg'
              OR option_row.name_zh = '套餐卤蛋'
              OR option_row.name_zh = '卤蛋'
            THEN 'combo_tea_egg'
            WHEN lower(coalesce(option_row.option_code, '')) = 'combo_fried_egg'
              OR option_row.name_zh = '套餐煎蛋'
              OR option_row.name_zh = '煎蛋'
            THEN 'combo_fried_egg'
            WHEN lower(coalesce(option_row.option_code, '')) = 'combo_edamame'
              OR option_row.name_zh = '套餐毛豆'
            THEN 'combo_edamame'
            WHEN lower(coalesce(option_row.option_code, '')) = 'combo_shredded_potato'
              OR option_row.name_zh = '套餐土豆丝'
            THEN 'combo_shredded_potato'
            WHEN lower(coalesce(option_row.option_code, '')) = 'combo_cucumber_salad'
              OR option_row.name_zh = '套餐拌黄瓜'
            THEN 'combo_cucumber_salad'
            ELSE NULL
        END AS component_code
    FROM public.menu_item_options option_row
    JOIN public.menu_items item ON item.id = option_row.menu_item_id
    WHERE option_row.is_active IS TRUE
),
enabled_components AS (
    SELECT DISTINCT store_id, component_group, component_code
    FROM existing_component_semantics
    WHERE component_group IS NOT NULL
      AND component_code IS NOT NULL
)
INSERT INTO public.store_combo_components (
    store_id,
    component_group,
    component_code,
    name_zh,
    name_en,
    enabled,
    display_order,
    created_at,
    updated_at
)
SELECT
    store_row.id,
    component.component_group,
    component.component_code,
    component.name_zh,
    component.name_en,
    enabled_component.component_code IS NOT NULL,
    component.display_order,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM public.stores store_row
CROSS JOIN canonical_components component
LEFT JOIN enabled_components enabled_component
    ON enabled_component.store_id = store_row.id
   AND enabled_component.component_group = component.component_group
   AND enabled_component.component_code = component.component_code;
