CREATE TABLE public.store_modules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    module_key character varying(96) NOT NULL,
    enabled boolean NOT NULL,
    source character varying(64) NOT NULL DEFAULT 'MIGRATION_DEFAULT',
    configuration_status character varying(64) NOT NULL DEFAULT 'CONFIGURED',
    profile_code character varying(96),
    profile_version character varying(64),
    metadata_json text NOT NULL DEFAULT '{}',
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_store_modules_store_module UNIQUE (store_id, module_key),
    CONSTRAINT fk_store_modules_store
        FOREIGN KEY (store_id) REFERENCES public.stores(id),
    CONSTRAINT chk_store_modules_module_key
        CHECK (module_key IN (
            'ORDERING_POS',
            'MENU',
            'MENU_MANAGEMENT',
            'TABLE_MANAGEMENT',
            'PRINTING',
            'ORDER_HISTORY',
            'REPORTING_CORE',
            'STAFF_ACCESS',
            'STORE_ADMINISTRATION',
            'KDS',
            'ANALYTICS_ADVANCED'
        )),
    CONSTRAINT chk_store_modules_source
        CHECK (source IN (
            'MIGRATION_DEFAULT',
            'SYSTEM_DEFAULT',
            'PROFILE_DEFAULT',
            'ADMIN_OVERRIDE'
        )),
    CONSTRAINT chk_store_modules_configuration_status
        CHECK (configuration_status IN (
            'CONFIGURED',
            'INCOMPLETE'
        )),
    CONSTRAINT chk_store_modules_metadata_json_object
        CHECK (metadata_json IS NOT NULL AND left(btrim(metadata_json), 1) = '{')
);

CREATE INDEX idx_store_modules_store
    ON public.store_modules (store_id);

CREATE INDEX idx_store_modules_module_key
    ON public.store_modules (module_key);

WITH canonical_modules AS (
    SELECT *
    FROM (VALUES
        ('ORDERING_POS', true, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"core_required"}'),
        ('MENU', true, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"core_required"}'),
        ('MENU_MANAGEMENT', true, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"core_required"}'),
        ('TABLE_MANAGEMENT', true, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"core_required"}'),
        ('PRINTING', true, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"core_required","legacy_runtime_fields":["stores.printing_enabled","stores.printing_mode"]}'),
        ('ORDER_HISTORY', true, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"core_required"}'),
        ('REPORTING_CORE', true, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"core_required","legacy_environment_flag":"app.features.analytics"}'),
        ('STAFF_ACCESS', true, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"core_required"}'),
        ('STORE_ADMINISTRATION', true, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"core_required"}'),
        ('KDS', false, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"optional_default_off"}'),
        ('ANALYTICS_ADVANCED', false, 'MIGRATION_DEFAULT', 'CONFIGURED', '{"default_rule":"optional_default_off"}')
    ) AS module(module_key, enabled, source, configuration_status, metadata_json)
)
INSERT INTO public.store_modules (
    store_id,
    module_key,
    enabled,
    source,
    configuration_status,
    profile_code,
    profile_version,
    metadata_json,
    created_at,
    updated_at
)
SELECT
    store_row.id,
    module.module_key,
    module.enabled,
    module.source,
    module.configuration_status,
    NULL,
    NULL,
    module.metadata_json,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM public.stores store_row
CROSS JOIN canonical_modules module;
