CREATE TABLE public.store_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_code character varying(96) NOT NULL,
    display_name character varying(255) NOT NULL,
    description text,
    status character varying(64) NOT NULL,
    provenance character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_store_profiles_profile_code UNIQUE (profile_code),
    CONSTRAINT chk_store_profiles_profile_code
        CHECK (profile_code ~ '^[A-Z0-9][A-Z0-9_:-]*$'),
    CONSTRAINT chk_store_profiles_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'REVIEWED', 'READY', 'RETIRED'))
);

CREATE TABLE public.store_profile_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id bigint NOT NULL,
    profile_version character varying(64) NOT NULL,
    status character varying(64) NOT NULL,
    schema_version character varying(64) NOT NULL,
    content_json text NOT NULL,
    fingerprint_sha256 character(64) NOT NULL,
    source_reference character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    published_at timestamp(6) without time zone,
    CONSTRAINT uq_store_profile_versions_profile_version UNIQUE (profile_id, profile_version),
    CONSTRAINT fk_store_profile_versions_profile
        FOREIGN KEY (profile_id) REFERENCES public.store_profiles(id),
    CONSTRAINT chk_store_profile_versions_version
        CHECK (profile_version ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$'),
    CONSTRAINT chk_store_profile_versions_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'REVIEWED', 'READY', 'RETIRED')),
    CONSTRAINT chk_store_profile_versions_schema
        CHECK (schema_version ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$'),
    CONSTRAINT chk_store_profile_versions_content_json_object
        CHECK (content_json IS NOT NULL AND left(btrim(content_json), 1) = '{'),
    CONSTRAINT chk_store_profile_versions_fingerprint
        CHECK (fingerprint_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE TABLE public.store_profile_artifacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_version_id bigint NOT NULL,
    artifact_type character varying(96) NOT NULL,
    artifact_code character varying(128) NOT NULL,
    artifact_version character varying(64) NOT NULL,
    content_json text NOT NULL,
    fingerprint_sha256 character(64) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_store_profile_artifacts_version_type_code UNIQUE (
        profile_version_id,
        artifact_type,
        artifact_code
    ),
    CONSTRAINT fk_store_profile_artifacts_version
        FOREIGN KEY (profile_version_id) REFERENCES public.store_profile_versions(id),
    CONSTRAINT chk_store_profile_artifacts_type
        CHECK (artifact_type IN (
            'MODULE_DEFAULTS',
            'MENU_TEMPLATE',
            'PRICING_POLICY',
            'COMBO_CONFIGURATION',
            'TABLE_TEMPLATE',
            'STATION_TEMPLATE',
            'LOGICAL_PRINTING_TOPOLOGY',
            'ROLE_ACCESS_DEFAULTS',
            'HARDWARE_REQUIREMENTS',
            'DEVICE_CAPABILITY_REQUIREMENTS',
            'OPERATIONAL_SETTINGS',
            'FEATURE_DEFAULTS'
        )),
    CONSTRAINT chk_store_profile_artifacts_code
        CHECK (artifact_code ~ '^[A-Z0-9][A-Z0-9_:-]*$'),
    CONSTRAINT chk_store_profile_artifacts_version
        CHECK (artifact_version ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$'),
    CONSTRAINT chk_store_profile_artifacts_content_json
        CHECK (content_json IS NOT NULL AND left(btrim(content_json), 1) IN ('{', '[')),
    CONSTRAINT chk_store_profile_artifacts_fingerprint
        CHECK (fingerprint_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_store_profile_versions_profile
    ON public.store_profile_versions (profile_id);

CREATE INDEX idx_store_profile_versions_status
    ON public.store_profile_versions (status);

CREATE INDEX idx_store_profile_artifacts_version
    ON public.store_profile_artifacts (profile_version_id);

CREATE INDEX idx_store_profile_artifacts_type
    ON public.store_profile_artifacts (artifact_type);

CREATE OR REPLACE FUNCTION public.prevent_published_store_profile_version_rewrite()
RETURNS trigger AS $$
BEGIN
    IF OLD.status IN ('PUBLISHED', 'REVIEWED', 'READY', 'RETIRED') THEN
        IF NEW.status NOT IN ('PUBLISHED', 'REVIEWED', 'READY', 'RETIRED')
            OR NEW.profile_id IS DISTINCT FROM OLD.profile_id
            OR NEW.profile_version IS DISTINCT FROM OLD.profile_version
            OR NEW.schema_version IS DISTINCT FROM OLD.schema_version
            OR NEW.content_json IS DISTINCT FROM OLD.content_json
            OR NEW.fingerprint_sha256 IS DISTINCT FROM OLD.fingerprint_sha256
            OR NEW.source_reference IS DISTINCT FROM OLD.source_reference
        THEN
            RAISE EXCEPTION 'STORE_PROFILE_VERSION_IMMUTABLE';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.reject_store_profile_artifact_insert_for_immutable_version()
RETURNS trigger AS $$
DECLARE
    parent_status character varying(64);
BEGIN
    SELECT status INTO parent_status
    FROM public.store_profile_versions
    WHERE id = NEW.profile_version_id;

    IF parent_status IN ('PUBLISHED', 'REVIEWED', 'READY', 'RETIRED') THEN
        RAISE EXCEPTION 'STORE_PROFILE_ARTIFACT_IMMUTABLE';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.reject_store_profile_artifact_delete_for_immutable_version()
RETURNS trigger AS $$
DECLARE
    parent_status character varying(64);
BEGIN
    SELECT status INTO parent_status
    FROM public.store_profile_versions
    WHERE id = OLD.profile_version_id;

    IF parent_status IN ('PUBLISHED', 'REVIEWED', 'READY', 'RETIRED') THEN
        RAISE EXCEPTION 'STORE_PROFILE_ARTIFACT_IMMUTABLE';
    END IF;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.prevent_published_store_profile_artifact_rewrite()
RETURNS trigger AS $$
DECLARE
    old_parent_status character varying(64);
    new_parent_status character varying(64);
BEGIN
    SELECT status INTO old_parent_status
    FROM public.store_profile_versions
    WHERE id = OLD.profile_version_id;

    SELECT status INTO new_parent_status
    FROM public.store_profile_versions
    WHERE id = NEW.profile_version_id;

    IF old_parent_status IN ('PUBLISHED', 'REVIEWED', 'READY', 'RETIRED')
        OR new_parent_status IN ('PUBLISHED', 'REVIEWED', 'READY', 'RETIRED')
    THEN
        IF NEW.profile_version_id IS DISTINCT FROM OLD.profile_version_id
            OR NEW.artifact_type IS DISTINCT FROM OLD.artifact_type
            OR NEW.artifact_code IS DISTINCT FROM OLD.artifact_code
            OR NEW.artifact_version IS DISTINCT FROM OLD.artifact_version
            OR NEW.content_json IS DISTINCT FROM OLD.content_json
            OR NEW.fingerprint_sha256 IS DISTINCT FROM OLD.fingerprint_sha256
        THEN
            RAISE EXCEPTION 'STORE_PROFILE_ARTIFACT_IMMUTABLE';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_store_profile_versions_immutable
BEFORE UPDATE ON public.store_profile_versions
FOR EACH ROW
EXECUTE FUNCTION public.prevent_published_store_profile_version_rewrite();

CREATE TRIGGER trg_store_profile_artifacts_immutable
BEFORE UPDATE ON public.store_profile_artifacts
FOR EACH ROW
EXECUTE FUNCTION public.prevent_published_store_profile_artifact_rewrite();

CREATE TRIGGER trg_store_profile_artifacts_no_insert_when_immutable
BEFORE INSERT ON public.store_profile_artifacts
FOR EACH ROW
EXECUTE FUNCTION public.reject_store_profile_artifact_insert_for_immutable_version();

CREATE TRIGGER trg_store_profile_artifacts_no_delete_when_immutable
BEFORE DELETE ON public.store_profile_artifacts
FOR EACH ROW
EXECUTE FUNCTION public.reject_store_profile_artifact_delete_for_immutable_version();
