CREATE TABLE public.store_combo_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    group_code character varying(64) NOT NULL,
    name_zh character varying(255) NOT NULL,
    name_en character varying(255) NOT NULL,
    selection_rule character varying(32) NOT NULL DEFAULT 'EXACTLY_ONE',
    required boolean NOT NULL DEFAULT true,
    enabled boolean NOT NULL DEFAULT true,
    display_order integer NOT NULL,
    default_component_code character varying(128),
    archived_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_store_combo_groups_store_code
        UNIQUE (store_id, group_code),
    CONSTRAINT fk_store_combo_groups_store
        FOREIGN KEY (store_id) REFERENCES public.stores(id),
    CONSTRAINT chk_store_combo_groups_selection_rule
        CHECK (selection_rule IN ('EXACTLY_ONE', 'OPTIONAL_ONE'))
);

CREATE INDEX idx_store_combo_groups_store_order
    ON public.store_combo_groups (store_id, display_order, id);

WITH legacy_groups AS (
    SELECT *
    FROM (VALUES
        ('COMBO_EGG', '蛋类', 'Egg', 'EXACTLY_ONE', true, true, 10),
        ('COMBO_SIDE', '小菜', 'Side', 'EXACTLY_ONE', true, true, 20)
    ) AS legacy_group(group_code, name_zh, name_en, selection_rule, required, enabled, display_order)
)
INSERT INTO public.store_combo_groups (
    store_id,
    group_code,
    name_zh,
    name_en,
    selection_rule,
    required,
    enabled,
    display_order,
    created_at,
    updated_at
)
SELECT
    store_row.id,
    legacy_group.group_code,
    legacy_group.name_zh,
    legacy_group.name_en,
    legacy_group.selection_rule,
    legacy_group.required,
    legacy_group.enabled,
    legacy_group.display_order,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM public.stores store_row
CROSS JOIN legacy_groups legacy_group
ON CONFLICT (store_id, group_code) DO NOTHING;

ALTER TABLE public.store_combo_components
    DROP CONSTRAINT IF EXISTS chk_store_combo_components_group;

ALTER TABLE public.store_combo_components
    DROP CONSTRAINT IF EXISTS chk_store_combo_components_code;

ALTER TABLE public.store_combo_components
    ADD COLUMN group_id bigint,
    ADD COLUMN linked_menu_item_id bigint,
    ADD COLUMN business_behavior character varying(32) NOT NULL DEFAULT 'NO_KITCHEN_TASK',
    ADD COLUMN archived_at timestamp(6) without time zone;

UPDATE public.store_combo_components component
SET group_id = combo_group.id
FROM public.store_combo_groups combo_group
WHERE combo_group.store_id = component.store_id
  AND combo_group.group_code = component.component_group;

ALTER TABLE public.store_combo_components
    ALTER COLUMN group_id SET NOT NULL;

ALTER TABLE public.store_combo_components
    ADD CONSTRAINT fk_store_combo_components_group
        FOREIGN KEY (group_id) REFERENCES public.store_combo_groups(id);

ALTER TABLE public.store_combo_components
    ADD CONSTRAINT fk_store_combo_components_linked_menu_item
        FOREIGN KEY (linked_menu_item_id) REFERENCES public.menu_items(id);

ALTER TABLE public.store_combo_components
    ADD CONSTRAINT chk_store_combo_components_business_behavior
        CHECK (business_behavior IN ('NO_KITCHEN_TASK', 'LINKED_MENU_ITEM', 'LEGACY_COMBO_SIDE_TASK'));

CREATE INDEX idx_store_combo_components_group_order
    ON public.store_combo_components (group_id, display_order, id);

CREATE INDEX idx_store_combo_components_linked_menu_item
    ON public.store_combo_components (linked_menu_item_id)
    WHERE linked_menu_item_id IS NOT NULL;

UPDATE public.store_combo_components component
SET linked_menu_item_id = menu_item.id,
    business_behavior = 'LEGACY_COMBO_SIDE_TASK',
    updated_at = CURRENT_TIMESTAMP
FROM public.menu_items menu_item
WHERE menu_item.store_id = component.store_id
  AND component.component_group = 'COMBO_SIDE'
  AND (
        (component.component_code = 'combo_edamame' AND menu_item.sku = 'edamame')
     OR (component.component_code = 'combo_shredded_potato' AND menu_item.sku = 'shredded_potato')
     OR (component.component_code = 'combo_cucumber_salad' AND menu_item.sku = 'cucumber_salad')
  );

WITH default_components AS (
    SELECT DISTINCT ON (component.store_id, component.component_group)
        component.store_id,
        component.component_group,
        component.component_code
    FROM public.store_combo_components component
    WHERE component.enabled IS TRUE
      AND component.archived_at IS NULL
    ORDER BY component.store_id, component.component_group, component.display_order, component.id
)
UPDATE public.store_combo_groups combo_group
SET default_component_code = default_component.component_code,
    updated_at = CURRENT_TIMESTAMP
FROM default_components default_component
WHERE default_component.store_id = combo_group.store_id
  AND default_component.component_group = combo_group.group_code;

ALTER TABLE public.stations
    ADD COLUMN name_zh character varying(255),
    ADD COLUMN name_en character varying(255),
    ADD COLUMN station_type character varying(32) NOT NULL DEFAULT 'KITCHEN',
    ADD COLUMN archived_at timestamp(6) without time zone;

UPDATE public.stations
SET name_zh = COALESCE(name_zh, name),
    name_en = COALESCE(name_en, name),
    updated_at = CURRENT_TIMESTAMP
WHERE name_zh IS NULL
   OR name_en IS NULL;

ALTER TABLE public.stations
    ADD CONSTRAINT chk_stations_station_type
        CHECK (station_type IN ('KITCHEN', 'BAR', 'COLD', 'PASS', 'OTHER'));

CREATE INDEX idx_stations_store_code
    ON public.stations (store_id, code);

CREATE INDEX idx_stations_store_active_order
    ON public.stations (store_id, is_active, sort_order, id);

CREATE INDEX idx_menu_categories_store_code
    ON public.menu_categories (store_id, code);

CREATE INDEX idx_menu_categories_store_active_order
    ON public.menu_categories (store_id, is_active, sort_order, id);
