-- V18__add_phase_b_master_menu_provisioning
-- Phase B Part 1: chain master menu identity, store lifecycle provenance,
-- and owner store provisioning ledger. Additive schema only.

ALTER TABLE public.stores
    ADD COLUMN store_kind character varying(32) NOT NULL DEFAULT 'BUSINESS',
    ADD COLUMN lifecycle_status character varying(32) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN provisioning_source character varying(64) NOT NULL DEFAULT 'LEGACY_EXISTING_STORE',
    ADD COLUMN provisioned_profile_code character varying(96),
    ADD COLUMN provisioned_profile_version character varying(64),
    ADD COLUMN provisioned_profile_fingerprint_sha256 character(64),
    ADD COLUMN provisioned_master_menu_key character varying(96),
    ADD COLUMN provisioned_master_menu_version character varying(64),
    ADD COLUMN provisioned_master_menu_fingerprint_sha256 character(64);

ALTER TABLE public.stores
    ADD CONSTRAINT chk_stores_store_kind
        CHECK (store_kind IN ('BUSINESS', 'VALIDATION_FIXTURE')),
    ADD CONSTRAINT chk_stores_lifecycle_status
        CHECK (lifecycle_status IN (
            'CONFIGURING',
            'READY_FOR_REVIEW',
            'ACTIVE',
            'INACTIVE',
            'PROVISIONING_FAILED'
        )),
    ADD CONSTRAINT chk_stores_provisioning_source
        CHECK (provisioning_source IN (
            'LEGACY_EXISTING_STORE',
            'PHASE_B_OWNER_PROVISIONING',
            'STAGING_VALIDATION'
        )),
    ADD CONSTRAINT chk_stores_provisioned_profile_fingerprint
        CHECK (
            provisioned_profile_fingerprint_sha256 IS NULL
            OR provisioned_profile_fingerprint_sha256 ~ '^[0-9a-f]{64}$'
        ),
    ADD CONSTRAINT chk_stores_provisioned_master_menu_fingerprint
        CHECK (
            provisioned_master_menu_fingerprint_sha256 IS NULL
            OR provisioned_master_menu_fingerprint_sha256 ~ '^[0-9a-f]{64}$'
        );

CREATE TABLE public.chain_master_menus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    master_menu_key character varying(96) NOT NULL,
    display_name character varying(255) NOT NULL,
    description text,
    status character varying(32) NOT NULL,
    provenance character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_chain_master_menus_org_key UNIQUE (organization_id, master_menu_key),
    CONSTRAINT fk_chain_master_menus_organization
        FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
    CONSTRAINT chk_chain_master_menus_key
        CHECK (master_menu_key ~ '^[A-Z0-9][A-Z0-9_:-]*$'),
    CONSTRAINT chk_chain_master_menus_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'RETIRED'))
);

CREATE TABLE public.chain_master_menu_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_menu_id bigint NOT NULL,
    version_key character varying(64) NOT NULL,
    status character varying(32) NOT NULL,
    schema_version character varying(64) NOT NULL,
    content_json text NOT NULL,
    fingerprint_sha256 character(64) NOT NULL,
    source_profile_code character varying(96) NOT NULL,
    source_profile_version character varying(64) NOT NULL,
    source_profile_fingerprint_sha256 character(64) NOT NULL,
    source_reference character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    published_at timestamp(6) without time zone,
    CONSTRAINT uq_chain_master_menu_versions_key UNIQUE (master_menu_id, version_key),
    CONSTRAINT uq_chain_master_menu_versions_fingerprint UNIQUE (master_menu_id, fingerprint_sha256),
    CONSTRAINT fk_chain_master_menu_versions_menu
        FOREIGN KEY (master_menu_id) REFERENCES public.chain_master_menus(id),
    CONSTRAINT chk_chain_master_menu_versions_version
        CHECK (version_key ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$'),
    CONSTRAINT chk_chain_master_menu_versions_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'RETIRED')),
    CONSTRAINT chk_chain_master_menu_versions_schema
        CHECK (schema_version = 'CHAIN_MASTER_MENU_V1'),
    CONSTRAINT chk_chain_master_menu_versions_content_json
        CHECK (content_json IS NOT NULL AND left(btrim(content_json), 1) = '{'),
    CONSTRAINT chk_chain_master_menu_versions_fingerprint
        CHECK (fingerprint_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_chain_master_menu_versions_profile_fingerprint
        CHECK (source_profile_fingerprint_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_chain_master_menu_versions_published_at
        CHECK ((status = 'PUBLISHED' AND published_at IS NOT NULL) OR status IN ('DRAFT', 'RETIRED'))
);

CREATE TABLE public.chain_master_menu_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_menu_version_id bigint NOT NULL,
    master_category_key character varying(128) NOT NULL,
    category_ref character varying(128) NOT NULL,
    code character varying(128),
    name character varying(255) NOT NULL,
    name_en character varying(255),
    name_zh character varying(255),
    sort_order integer NOT NULL DEFAULT 0,
    default_active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_chain_master_menu_categories_key UNIQUE (
        master_menu_version_id,
        master_category_key
    ),
    CONSTRAINT uq_chain_master_menu_categories_ref UNIQUE (
        master_menu_version_id,
        category_ref
    ),
    CONSTRAINT fk_chain_master_menu_categories_version
        FOREIGN KEY (master_menu_version_id) REFERENCES public.chain_master_menu_versions(id),
    CONSTRAINT chk_chain_master_menu_categories_key
        CHECK (master_category_key ~ '^[A-Za-z0-9][A-Za-z0-9_:-]*$'),
    CONSTRAINT chk_chain_master_menu_categories_ref
        CHECK (category_ref ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$')
);

CREATE TABLE public.chain_master_menu_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_menu_version_id bigint NOT NULL,
    master_product_key character varying(128) NOT NULL,
    item_ref character varying(128) NOT NULL,
    sku character varying(128) NOT NULL,
    master_category_key character varying(128) NOT NULL,
    station_ref character varying(128),
    name character varying(255) NOT NULL,
    name_en character varying(255),
    name_zh character varying(255),
    item_type character varying(64),
    base_price numeric(10, 2),
    cost_per_item numeric(10, 2),
    sort_order integer NOT NULL DEFAULT 0,
    default_active boolean NOT NULL DEFAULT true,
    default_sold_out boolean NOT NULL DEFAULT false,
    combo_allowed boolean NOT NULL DEFAULT false,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_chain_master_menu_products_key UNIQUE (
        master_menu_version_id,
        master_product_key
    ),
    CONSTRAINT uq_chain_master_menu_products_ref UNIQUE (
        master_menu_version_id,
        item_ref
    ),
    CONSTRAINT fk_chain_master_menu_products_version
        FOREIGN KEY (master_menu_version_id) REFERENCES public.chain_master_menu_versions(id),
    CONSTRAINT chk_chain_master_menu_products_key
        CHECK (master_product_key ~ '^[A-Za-z0-9][A-Za-z0-9_:-]*$'),
    CONSTRAINT chk_chain_master_menu_products_ref
        CHECK (item_ref ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$'),
    CONSTRAINT chk_chain_master_menu_products_price
        CHECK (base_price IS NULL OR base_price >= 0),
    CONSTRAINT chk_chain_master_menu_products_cost
        CHECK (cost_per_item IS NULL OR cost_per_item >= 0)
);

CREATE TABLE public.chain_master_menu_options (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_menu_version_id bigint NOT NULL,
    master_option_key character varying(128) NOT NULL,
    option_ref character varying(128) NOT NULL,
    master_product_key character varying(128) NOT NULL,
    parent_master_option_key character varying(128),
    option_type character varying(64),
    option_group character varying(96),
    code character varying(128),
    name character varying(255) NOT NULL,
    name_en character varying(255),
    name_zh character varying(255),
    price_delta numeric(10, 2) NOT NULL DEFAULT 0,
    sort_order integer NOT NULL DEFAULT 0,
    default_active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_chain_master_menu_options_key UNIQUE (
        master_menu_version_id,
        master_option_key
    ),
    CONSTRAINT uq_chain_master_menu_options_ref UNIQUE (
        master_menu_version_id,
        option_ref
    ),
    CONSTRAINT fk_chain_master_menu_options_version
        FOREIGN KEY (master_menu_version_id) REFERENCES public.chain_master_menu_versions(id),
    CONSTRAINT chk_chain_master_menu_options_key
        CHECK (master_option_key ~ '^[A-Za-z0-9][A-Za-z0-9_:-]*$'),
    CONSTRAINT chk_chain_master_menu_options_ref
        CHECK (option_ref ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$')
);

CREATE TABLE public.store_menu_master_mappings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    master_menu_version_id bigint NOT NULL,
    entity_type character varying(32) NOT NULL,
    local_entity_id bigint NOT NULL,
    master_category_key character varying(128),
    master_product_key character varying(128),
    master_option_key character varying(128),
    origin character varying(32) NOT NULL,
    mapping_status character varying(32) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_store_menu_master_mappings_local UNIQUE (
        store_id,
        entity_type,
        local_entity_id
    ),
    CONSTRAINT fk_store_menu_master_mappings_store
        FOREIGN KEY (store_id) REFERENCES public.stores(id),
    CONSTRAINT fk_store_menu_master_mappings_version
        FOREIGN KEY (master_menu_version_id) REFERENCES public.chain_master_menu_versions(id),
    CONSTRAINT chk_store_menu_master_mappings_entity_type
        CHECK (entity_type IN ('CATEGORY', 'ITEM', 'OPTION')),
    CONSTRAINT chk_store_menu_master_mappings_origin
        CHECK (origin IN ('MASTER', 'STORE_ONLY')),
    CONSTRAINT chk_store_menu_master_mappings_status
        CHECK (mapping_status IN ('ACTIVE', 'LOCALLY_DEACTIVATED', 'STORE_ONLY')),
    CONSTRAINT chk_store_menu_master_mappings_identity
        CHECK (
            (
                origin = 'STORE_ONLY'
                AND mapping_status = 'STORE_ONLY'
                AND master_category_key IS NULL
                AND master_product_key IS NULL
                AND master_option_key IS NULL
            )
            OR (
                origin = 'MASTER'
                AND mapping_status IN ('ACTIVE', 'LOCALLY_DEACTIVATED')
                AND (
                    (entity_type = 'CATEGORY' AND master_category_key IS NOT NULL
                        AND master_product_key IS NULL AND master_option_key IS NULL)
                    OR (entity_type = 'ITEM' AND master_product_key IS NOT NULL
                        AND master_option_key IS NULL)
                    OR (entity_type = 'OPTION' AND master_option_key IS NOT NULL)
                )
            )
        )
);

CREATE TABLE public.owner_store_provisioning_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    idempotency_key character varying(255) NOT NULL,
    request_fingerprint character(64) NOT NULL,
    status character varying(32) NOT NULL,
    store_id bigint,
    store_name character varying(255) NOT NULL,
    store_code character varying(255) NOT NULL,
    profile_code character varying(96) NOT NULL,
    profile_version character varying(64) NOT NULL,
    profile_fingerprint_sha256 character(64) NOT NULL,
    master_menu_key character varying(96) NOT NULL,
    master_menu_version character varying(64) NOT NULL,
    master_menu_fingerprint_sha256 character(64) NOT NULL,
    validation_status character varying(32) NOT NULL,
    result_code character varying(64),
    error_code character varying(64),
    created_station_count integer,
    created_category_count integer,
    created_item_count integer,
    created_option_count integer,
    created_pricing_policy_count integer,
    created_combo_component_count integer,
    created_printing_rule_count integer,
    actor_user_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone,
    CONSTRAINT uq_owner_store_provisioning_organization_key UNIQUE (
        organization_id,
        idempotency_key
    ),
    CONSTRAINT fk_owner_store_provisioning_organization
        FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
    CONSTRAINT fk_owner_store_provisioning_store
        FOREIGN KEY (store_id) REFERENCES public.stores(id),
    CONSTRAINT chk_owner_store_provisioning_status
        CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT chk_owner_store_provisioning_request_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_owner_store_provisioning_profile_fingerprint
        CHECK (profile_fingerprint_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_owner_store_provisioning_master_menu_fingerprint
        CHECK (master_menu_fingerprint_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_owner_store_provisioning_validation_status
        CHECK (validation_status IN ('PENDING', 'PASSED', 'FAILED'))
);

ALTER TABLE public.store_profile_artifacts
    DROP CONSTRAINT chk_store_profile_artifacts_type;

ALTER TABLE public.store_profile_artifacts
    ADD CONSTRAINT chk_store_profile_artifacts_type
        CHECK (artifact_type IN (
            'MODULE_DEFAULTS',
            'MENU_TEMPLATE',
            'PRICING_POLICY',
            'COMBO_CONFIGURATION',
            'TABLE_TEMPLATE',
            'STATION_TEMPLATE',
            'LOGICAL_PRINTING_TOPOLOGY',
            'PRINTING_DISPLAY_RULES',
            'ROLE_ACCESS_DEFAULTS',
            'HARDWARE_REQUIREMENTS',
            'DEVICE_CAPABILITY_REQUIREMENTS',
            'OPERATIONAL_SETTINGS',
            'FEATURE_DEFAULTS'
        ));

CREATE INDEX idx_stores_store_kind_lifecycle
    ON public.stores (store_kind, lifecycle_status);

CREATE INDEX idx_stores_provisioned_profile
    ON public.stores (provisioned_profile_code, provisioned_profile_version)
    WHERE provisioned_profile_code IS NOT NULL;

CREATE INDEX idx_stores_provisioned_master_menu
    ON public.stores (provisioned_master_menu_key, provisioned_master_menu_version)
    WHERE provisioned_master_menu_key IS NOT NULL;

CREATE INDEX idx_chain_master_menus_organization_status
    ON public.chain_master_menus (organization_id, status);

CREATE INDEX idx_chain_master_menu_versions_menu_status
    ON public.chain_master_menu_versions (master_menu_id, status, version_key);

CREATE INDEX idx_chain_master_menu_categories_version
    ON public.chain_master_menu_categories (master_menu_version_id, sort_order);

CREATE INDEX idx_chain_master_menu_products_version
    ON public.chain_master_menu_products (master_menu_version_id, sort_order);

CREATE INDEX idx_chain_master_menu_products_sku
    ON public.chain_master_menu_products (master_menu_version_id, sku);

CREATE INDEX idx_chain_master_menu_options_version
    ON public.chain_master_menu_options (master_menu_version_id, sort_order);

CREATE INDEX idx_chain_master_menu_options_product
    ON public.chain_master_menu_options (master_menu_version_id, master_product_key);

CREATE INDEX idx_store_menu_master_mappings_store_version
    ON public.store_menu_master_mappings (store_id, master_menu_version_id);

CREATE INDEX idx_store_menu_master_mappings_master_identity
    ON public.store_menu_master_mappings (
        master_menu_version_id,
        master_category_key,
        master_product_key,
        master_option_key
    );

CREATE INDEX idx_owner_store_provisioning_store
    ON public.owner_store_provisioning_requests (store_id)
    WHERE store_id IS NOT NULL;

CREATE INDEX idx_owner_store_provisioning_status
    ON public.owner_store_provisioning_requests (organization_id, status, created_at);

CREATE OR REPLACE FUNCTION public.enforce_chain_master_menu_version_immutable()
RETURNS trigger AS $$
BEGIN
    IF OLD.status IN ('PUBLISHED', 'RETIRED') AND (
            NEW.master_menu_id IS DISTINCT FROM OLD.master_menu_id
            OR NEW.version_key IS DISTINCT FROM OLD.version_key
            OR (
                NEW.status IS DISTINCT FROM OLD.status
                AND NOT (OLD.status = 'PUBLISHED' AND NEW.status = 'RETIRED')
            )
            OR NEW.schema_version IS DISTINCT FROM OLD.schema_version
            OR NEW.content_json IS DISTINCT FROM OLD.content_json
            OR NEW.fingerprint_sha256 IS DISTINCT FROM OLD.fingerprint_sha256
            OR NEW.source_profile_code IS DISTINCT FROM OLD.source_profile_code
            OR NEW.source_profile_version IS DISTINCT FROM OLD.source_profile_version
            OR NEW.source_profile_fingerprint_sha256 IS DISTINCT FROM OLD.source_profile_fingerprint_sha256
            OR NEW.source_reference IS DISTINCT FROM OLD.source_reference
            OR NEW.published_at IS DISTINCT FROM OLD.published_at
        ) THEN
        RAISE EXCEPTION 'CHAIN_MASTER_MENU_VERSION_IMMUTABLE';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_chain_master_menu_versions_immutable
BEFORE UPDATE ON public.chain_master_menu_versions
FOR EACH ROW
EXECUTE FUNCTION public.enforce_chain_master_menu_version_immutable();
