--
-- PostgreSQL database dump
--
-- Restaurant POS Flyway baseline.
-- Generated from the current local PostgreSQL schema with:
-- pg_dump --schema-only --no-owner --no-privileges --no-comments --schema=public
--
-- This migration intentionally captures the current schema as-is.
-- Do not add data, destructive changes, aggressive foreign keys, or
-- production data repair logic to V1. Follow-up migrations should be
-- reviewed separately.


-- Dumped from database version 18.3 (Homebrew)
-- Dumped by pg_dump version 18.3 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: analytics_alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analytics_alerts (
    id bigint NOT NULL,
    alert_type character varying(255),
    comparison_value numeric(38,2),
    created_at timestamp(6) without time zone,
    is_resolved boolean,
    message character varying(255),
    metric_value numeric(38,2),
    organization_id bigint,
    resolved_at timestamp(6) without time zone,
    severity character varying(255),
    store_id bigint,
    title character varying(255)
);


--
-- Name: analytics_alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.analytics_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    actor_name_snapshot character varying(255),
    actor_role_snapshot character varying(255),
    actor_user_id bigint,
    created_at timestamp(6) without time zone,
    entity_id bigint,
    entity_type character varying(255),
    metadata_json text,
    request_ip character varying(255),
    store_id bigint,
    summary character varying(1000),
    user_agent character varying(1000)
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dining_tables; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dining_tables (
    id bigint NOT NULL,
    area_name character varying(255),
    capacity integer,
    created_at timestamp(6) without time zone,
    is_active boolean,
    store_id bigint,
    supports_split boolean,
    table_code character varying(255),
    table_name character varying(255),
    updated_at timestamp(6) without time zone,
    sort_order integer,
    table_config character varying(255)
);


--
-- Name: dining_tables_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dining_tables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dining_tables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: frontdesk_beverage_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.frontdesk_beverage_items (
    id bigint NOT NULL,
    cancelled_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    item_name_snapshot_en character varying(255),
    item_name_snapshot_zh character varying(255),
    order_id bigint,
    order_item_id bigint,
    quantity integer,
    ready_at timestamp(6) without time zone,
    served_at timestamp(6) without time zone,
    special_instructions_snapshot character varying(255),
    started_at timestamp(6) without time zone,
    status character varying(255),
    store_id bigint
);


--
-- Name: frontdesk_beverage_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.frontdesk_beverage_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.frontdesk_beverage_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_items (
    id bigint NOT NULL,
    code character varying(255),
    created_at timestamp(6) without time zone,
    current_stock numeric(38,2),
    default_prep_batch numeric(38,2),
    is_active boolean,
    is_key_item boolean,
    item_level character varying(255),
    item_type character varying(255),
    name character varying(255),
    safety_stock numeric(38,2),
    store_id bigint,
    unit character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: inventory_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_transactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    inventory_item_id bigint,
    operated_by bigint,
    qty_change numeric(38,2),
    remarks character varying(255),
    source_id bigint,
    source_type character varying(255),
    stock_after numeric(38,2),
    stock_before numeric(38,2),
    txn_type character varying(255)
);


--
-- Name: inventory_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kitchen_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kitchen_tasks (
    id bigint NOT NULL,
    cancelled_at timestamp(6) without time zone,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    item_name_snapshot_en character varying(255),
    item_name_snapshot_zh character varying(255),
    order_id bigint,
    order_item_id bigint,
    priority integer,
    quantity integer,
    served_at timestamp(6) without time zone,
    special_instructions_snapshot character varying(255),
    started_at timestamp(6) without time zone,
    station_code character varying(255),
    status character varying(255),
    store_id bigint
);


--
-- Name: kitchen_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.kitchen_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kitchen_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_categories (
    id bigint NOT NULL,
    code character varying(255),
    created_at timestamp(6) without time zone,
    is_active boolean,
    name_en character varying(255),
    name_zh character varying(255),
    sort_order integer,
    store_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: menu_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_item_bom; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_item_bom (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    inventory_item_id bigint,
    menu_item_id bigint,
    qty_per_unit numeric(38,2),
    updated_at timestamp(6) without time zone
);


--
-- Name: menu_item_bom_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_item_bom ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_item_bom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_item_option_bom; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_item_option_bom (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    inventory_item_id bigint,
    menu_item_option_id bigint,
    qty_per_unit numeric(38,2),
    updated_at timestamp(6) without time zone
);


--
-- Name: menu_item_option_bom_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_item_option_bom ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_item_option_bom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_item_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_item_options (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean,
    menu_item_id bigint,
    name_en character varying(255),
    name_zh character varying(255),
    option_type character varying(255),
    price_delta numeric(38,2),
    updated_at timestamp(6) without time zone,
    option_code character varying(255),
    option_group character varying(255),
    parent_option_id bigint,
    sort_order integer
);


--
-- Name: menu_item_options_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_item_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_item_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_item_sales_summary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_item_sales_summary (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    item_name_snapshot_en character varying(255),
    item_name_snapshot_zh character varying(255),
    menu_item_id bigint,
    order_count integer,
    organization_id bigint,
    quantity_sold integer,
    sales_amount numeric(38,2),
    store_id bigint,
    summary_date date,
    updated_at timestamp(6) without time zone,
    total_cost numeric(38,2),
    total_profit numeric(38,2)
);


--
-- Name: menu_item_sales_summary_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_item_sales_summary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_item_sales_summary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_items (
    id bigint NOT NULL,
    base_price numeric(38,2),
    category_id bigint,
    created_at timestamp(6) without time zone,
    is_active boolean,
    is_sold_out boolean,
    item_type character varying(255),
    name_en character varying(255),
    name_zh character varying(255),
    sku character varying(255),
    station_id bigint,
    store_id bigint,
    updated_at timestamp(6) without time zone,
    cost_per_item numeric(38,2)
);


--
-- Name: menu_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_item_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_item_options (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    option_id bigint,
    option_name_snapshot_en character varying(255),
    option_name_snapshot_zh character varying(255),
    option_type_snapshot character varying(255),
    order_item_id bigint,
    price_delta numeric(38,2),
    quantity integer,
    option_code_snapshot character varying(255),
    option_group_snapshot character varying(255),
    parent_option_id_snapshot bigint
);


--
-- Name: order_item_options_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_item_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    category_code_snapshot character varying(255),
    combo_group_no integer,
    combo_role character varying(255),
    created_at timestamp(6) without time zone,
    is_modified_after_submit boolean,
    item_name_snapshot_en character varying(255),
    item_name_snapshot_zh character varying(255),
    line_amount numeric(38,2),
    menu_item_id bigint,
    modified_after_submit_at timestamp(6) without time zone,
    notes character varying(255),
    order_id bigint,
    quantity integer,
    status character varying(255),
    unit_price numeric(38,2),
    updated_at timestamp(6) without time zone,
    added_revision integer,
    order_update_batch_id bigint
);


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_update_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_update_batches (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by bigint,
    idempotency_key character varying(255) NOT NULL,
    order_id bigint NOT NULL,
    revision integer NOT NULL
);


--
-- Name: order_update_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_update_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_update_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    created_by bigint,
    discount_amount numeric(38,2),
    is_modified_after_submit boolean,
    modified_after_submit_at timestamp(6) without time zone,
    modified_after_submit_by bigint,
    order_no character varying(255),
    order_type character varying(255),
    pickup_no character varying(255),
    ready_at timestamp(6) without time zone,
    status character varying(255),
    store_id bigint,
    submitted_at timestamp(6) without time zone,
    subtotal_amount numeric(38,2),
    table_no character varying(255),
    total_amount numeric(38,2),
    updated_at timestamp(6) without time zone,
    current_revision integer
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organization_memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_memberships (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean,
    organization_id bigint,
    role_code character varying(255),
    role_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint
);


--
-- Name: organization_memberships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organization_memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organizations (
    id bigint NOT NULL,
    code character varying(255),
    created_at timestamp(6) without time zone,
    name character varying(255),
    status character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: organizations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prep_recipe_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prep_recipe_details (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    input_inventory_item_id bigint,
    input_qty numeric(38,2),
    input_unit character varying(255),
    prep_recipe_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: prep_recipe_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.prep_recipe_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prep_recipe_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prep_recipes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prep_recipes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean,
    output_inventory_item_id bigint,
    output_qty numeric(38,2),
    output_unit character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: prep_recipes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.prep_recipes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prep_recipes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: print_job_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.print_job_attempts (
    id bigint NOT NULL,
    attempt_number integer,
    error_message text,
    finished_at timestamp(6) without time zone,
    print_job_id bigint,
    printer_id bigint,
    started_at timestamp(6) without time zone,
    status character varying(255),
    client_attempt_token character varying(255),
    device_id bigint,
    error_code character varying(255),
    raw_result text,
    transport_type character varying(255)
);


--
-- Name: print_job_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.print_job_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.print_job_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: print_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.print_jobs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    error_code character varying(255),
    error_message text,
    failed_at timestamp(6) without time zone,
    last_attempt_at timestamp(6) without time zone,
    max_retry_count integer,
    module_code character varying(255),
    order_id bigint,
    organization_id bigint,
    payload_snapshot text,
    printed_at timestamp(6) without time zone,
    printer_id bigint,
    receipt_type character varying(255),
    rendered_text_snapshot text,
    requested_by_user_id bigint,
    retry_count integer,
    status character varying(255),
    store_id bigint,
    updated_at timestamp(6) without time zone,
    order_update_batch_id bigint,
    claim_expires_at timestamp(6) without time zone,
    claimed_at timestamp(6) without time zone,
    claimed_by_device_id bigint,
    client_attempt_token character varying(255),
    escpos_payload_base64 text,
    execution_mode character varying(255),
    printed_by_device_id bigint
);


--
-- Name: print_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.print_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.print_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: printer_assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.printer_assignments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    enabled boolean,
    module_code character varying(255),
    printer_id bigint,
    store_id bigint,
    updated_at timestamp(6) without time zone,
    font_size character varying(255),
    takeout_receipt_copies integer
);


--
-- Name: printer_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.printer_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.printer_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: printer_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.printer_configs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    enabled boolean,
    ip_address character varying(255),
    name character varying(255),
    paper_width_mm integer,
    port integer,
    printer_type character varying(255),
    store_id bigint,
    timeout_ms integer,
    updated_at timestamp(6) without time zone,
    escpos_code_page integer,
    text_encoding character varying(255),
    font_size_mode character varying(255),
    font_size character varying(255),
    last_connection_error text,
    last_connection_failed_at timestamp(6) without time zone,
    last_connection_success_at timestamp(6) without time zone,
    last_error_message text,
    last_failed_print_at timestamp(6) without time zone,
    last_successful_print_at timestamp(6) without time zone
);


--
-- Name: printer_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.printer_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.printer_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: production_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.production_tasks (
    id bigint NOT NULL,
    cancelled_at timestamp(6) without time zone,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    item_name_snapshot_en character varying(255),
    item_name_snapshot_zh character varying(255),
    order_id bigint,
    order_item_id bigint,
    priority integer,
    quantity integer,
    ready_at timestamp(6) without time zone,
    served_at timestamp(6) without time zone,
    source_id bigint,
    source_type character varying(255),
    special_instructions_snapshot character varying(255),
    started_at timestamp(6) without time zone,
    station_code character varying(255),
    status character varying(255),
    store_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: production_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.production_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receipt_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.receipt_templates (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_default boolean,
    store_id bigint,
    template_code character varying(255),
    template_json text,
    template_name character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: receipt_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.receipt_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receipt_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    created_by_ip character varying(255),
    expires_at timestamp(6) without time zone NOT NULL,
    revoked_at timestamp(6) without time zone,
    store_id bigint,
    token_hash character varying(255) NOT NULL,
    user_agent character varying(1000),
    user_id bigint NOT NULL
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurant_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.restaurant_templates (
    id bigint NOT NULL,
    code character varying(255),
    created_at timestamp(6) without time zone,
    default_dining_table_layout_rules_json text,
    default_kds_display_rules_json text,
    default_menu_category_structure_json text,
    default_role_setup_json text,
    default_station_setup_json text,
    description character varying(255),
    is_active boolean,
    name character varying(255),
    organization_id bigint,
    source_store_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: restaurant_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.restaurant_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurant_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    id bigint NOT NULL,
    capability_code character varying(255),
    created_at timestamp(6) without time zone,
    feature_package character varying(255) NOT NULL,
    is_allowed boolean,
    permission character varying(255) NOT NULL,
    role_id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: role_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.role_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    code character varying(255),
    created_at timestamp(6) without time zone,
    name character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_daily_summary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_daily_summary (
    id bigint NOT NULL,
    average_order_value numeric(38,2),
    cancelled_order_count integer,
    completed_order_count integer,
    created_at timestamp(6) without time zone,
    gross_sales numeric(38,2),
    net_sales numeric(38,2),
    order_count integer,
    organization_id bigint,
    store_id bigint,
    summary_date date,
    updated_at timestamp(6) without time zone,
    profit_margin numeric(38,2),
    total_cost numeric(38,2),
    total_profit numeric(38,2)
);


--
-- Name: sales_daily_summary_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_daily_summary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_daily_summary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_hourly_summary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_hourly_summary (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    hour_of_day integer,
    order_count integer,
    organization_id bigint,
    sales_amount numeric(38,2),
    store_id bigint,
    summary_date date,
    updated_at timestamp(6) without time zone
);


--
-- Name: sales_hourly_summary_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_hourly_summary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_hourly_summary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stations (
    id bigint NOT NULL,
    code character varying(255),
    created_at timestamp(6) without time zone,
    is_active boolean,
    name character varying(255),
    sort_order integer,
    store_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: stations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store_devices (
    id bigint NOT NULL,
    app_version character varying(255),
    created_at timestamp(6) without time zone,
    device_name character varying(255),
    device_token_hash character varying(255),
    device_type character varying(255),
    is_active boolean,
    last_seen_at timestamp(6) without time zone,
    organization_id bigint,
    platform character varying(255),
    status character varying(255),
    store_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: store_devices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_kds_display_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store_kds_display_configs (
    id bigint NOT NULL,
    card_size_mode character varying(255),
    config_json text,
    created_at timestamp(6) without time zone,
    density_mode character varying(255),
    header_layout character varying(255),
    screen_code character varying(255),
    store_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: store_kds_display_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store_kds_display_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_kds_display_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store_memberships (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean,
    organization_id bigint,
    role_code character varying(255),
    role_id bigint,
    store_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint
);


--
-- Name: store_memberships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store_memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_performance_summary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store_performance_summary (
    id bigint NOT NULL,
    active_order_count integer,
    average_order_value numeric(38,2),
    created_at timestamp(6) without time zone,
    order_count integer,
    organization_id bigint,
    sales_amount numeric(38,2),
    store_id bigint,
    summary_date date,
    updated_at timestamp(6) without time zone
);


--
-- Name: store_performance_summary_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store_performance_summary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_performance_summary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stores (
    id bigint NOT NULL,
    code character varying(255),
    created_at timestamp(6) without time zone,
    enable_bar_kitchen_tasks boolean,
    name character varying(255),
    status character varying(255),
    updated_at timestamp(6) without time zone,
    organization_id bigint,
    printing_enabled boolean,
    printing_mode character varying(255)
);


--
-- Name: stores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_credentials (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean,
    login_identifier character varying(255) NOT NULL,
    password_algorithm character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    password_updated_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: user_credentials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_credentials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_credentials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_stations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_stations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean,
    is_primary boolean,
    station_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint
);


--
-- Name: user_stations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_stations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_stations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    full_name character varying(255),
    phone character varying(255),
    role_id bigint,
    status character varying(255),
    store_id bigint,
    updated_at timestamp(6) without time zone,
    username character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analytics_alerts analytics_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analytics_alerts
    ADD CONSTRAINT analytics_alerts_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: dining_tables dining_tables_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dining_tables
    ADD CONSTRAINT dining_tables_pkey PRIMARY KEY (id);


--
-- Name: frontdesk_beverage_items frontdesk_beverage_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.frontdesk_beverage_items
    ADD CONSTRAINT frontdesk_beverage_items_pkey PRIMARY KEY (id);


--
-- Name: inventory_items inventory_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT inventory_items_pkey PRIMARY KEY (id);


--
-- Name: inventory_transactions inventory_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_transactions
    ADD CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id);


--
-- Name: kitchen_tasks kitchen_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kitchen_tasks
    ADD CONSTRAINT kitchen_tasks_pkey PRIMARY KEY (id);


--
-- Name: menu_categories menu_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_categories
    ADD CONSTRAINT menu_categories_pkey PRIMARY KEY (id);


--
-- Name: menu_item_bom menu_item_bom_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_item_bom
    ADD CONSTRAINT menu_item_bom_pkey PRIMARY KEY (id);


--
-- Name: menu_item_option_bom menu_item_option_bom_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_item_option_bom
    ADD CONSTRAINT menu_item_option_bom_pkey PRIMARY KEY (id);


--
-- Name: menu_item_options menu_item_options_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_item_options
    ADD CONSTRAINT menu_item_options_pkey PRIMARY KEY (id);


--
-- Name: menu_item_sales_summary menu_item_sales_summary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_item_sales_summary
    ADD CONSTRAINT menu_item_sales_summary_pkey PRIMARY KEY (id);


--
-- Name: menu_items menu_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_items
    ADD CONSTRAINT menu_items_pkey PRIMARY KEY (id);


--
-- Name: order_item_options order_item_options_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item_options
    ADD CONSTRAINT order_item_options_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: order_update_batches order_update_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_update_batches
    ADD CONSTRAINT order_update_batches_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: organization_memberships organization_memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_memberships
    ADD CONSTRAINT organization_memberships_pkey PRIMARY KEY (id);


--
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);


--
-- Name: prep_recipe_details prep_recipe_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prep_recipe_details
    ADD CONSTRAINT prep_recipe_details_pkey PRIMARY KEY (id);


--
-- Name: prep_recipes prep_recipes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prep_recipes
    ADD CONSTRAINT prep_recipes_pkey PRIMARY KEY (id);


--
-- Name: print_job_attempts print_job_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.print_job_attempts
    ADD CONSTRAINT print_job_attempts_pkey PRIMARY KEY (id);


--
-- Name: print_jobs print_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.print_jobs
    ADD CONSTRAINT print_jobs_pkey PRIMARY KEY (id);


--
-- Name: printer_assignments printer_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.printer_assignments
    ADD CONSTRAINT printer_assignments_pkey PRIMARY KEY (id);


--
-- Name: printer_configs printer_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.printer_configs
    ADD CONSTRAINT printer_configs_pkey PRIMARY KEY (id);


--
-- Name: production_tasks production_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_tasks
    ADD CONSTRAINT production_tasks_pkey PRIMARY KEY (id);


--
-- Name: receipt_templates receipt_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receipt_templates
    ADD CONSTRAINT receipt_templates_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: restaurant_templates restaurant_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurant_templates
    ADD CONSTRAINT restaurant_templates_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sales_daily_summary sales_daily_summary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_daily_summary
    ADD CONSTRAINT sales_daily_summary_pkey PRIMARY KEY (id);


--
-- Name: sales_hourly_summary sales_hourly_summary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_hourly_summary
    ADD CONSTRAINT sales_hourly_summary_pkey PRIMARY KEY (id);


--
-- Name: stations stations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stations
    ADD CONSTRAINT stations_pkey PRIMARY KEY (id);


--
-- Name: store_devices store_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_devices
    ADD CONSTRAINT store_devices_pkey PRIMARY KEY (id);


--
-- Name: store_kds_display_configs store_kds_display_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_kds_display_configs
    ADD CONSTRAINT store_kds_display_configs_pkey PRIMARY KEY (id);


--
-- Name: store_memberships store_memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_memberships
    ADD CONSTRAINT store_memberships_pkey PRIMARY KEY (id);


--
-- Name: store_performance_summary store_performance_summary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_performance_summary
    ADD CONSTRAINT store_performance_summary_pkey PRIMARY KEY (id);


--
-- Name: stores stores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (id);


--
-- Name: order_update_batches uk_order_update_batch_idempotency; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_update_batches
    ADD CONSTRAINT uk_order_update_batch_idempotency UNIQUE (order_id, idempotency_key);


--
-- Name: order_update_batches uk_order_update_batch_revision; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_update_batches
    ADD CONSTRAINT uk_order_update_batch_revision UNIQUE (order_id, revision);


--
-- Name: organization_memberships uk_org_membership_user_org; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_memberships
    ADD CONSTRAINT uk_org_membership_user_org UNIQUE (user_id, organization_id);


--
-- Name: store_memberships uk_store_membership_user_store; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_memberships
    ADD CONSTRAINT uk_store_membership_user_store UNIQUE (user_id, store_id);


--
-- Name: user_credentials ukbx9rcwaqt8ybj9vsahxtechs5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_credentials
    ADD CONSTRAINT ukbx9rcwaqt8ybj9vsahxtechs5 UNIQUE (login_identifier);


--
-- Name: refresh_tokens uko2mlirhldriil2y7krapq4frt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uko2mlirhldriil2y7krapq4frt UNIQUE (token_hash);


--
-- Name: user_credentials user_credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_credentials
    ADD CONSTRAINT user_credentials_pkey PRIMARY KEY (id);


--
-- Name: user_stations user_stations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_stations
    ADD CONSTRAINT user_stations_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: order_item_options fk_order_item_options_order_item_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item_options
    ADD CONSTRAINT fk_order_item_options_order_item_id FOREIGN KEY (order_item_id) REFERENCES public.order_items(id);


--
-- Name: order_items fk_order_items_order_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- PostgreSQL database dump complete
--

