-- V23__add_phase_b_part2_readiness_and_activation
-- Phase B Part 2 only. All state is additive, Store-scoped and sanitized.
-- No credentials, printer endpoints, device tokens or Production data belong here.

CREATE TABLE store_readiness_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    readiness_fingerprint CHAR(64) NOT NULL,
    evidence_json TEXT NOT NULL,
    checked_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_store_readiness_evidence_store UNIQUE (store_id)
);

CREATE INDEX idx_store_readiness_evidence_scope
    ON store_readiness_evidence (organization_id, store_id, status);

CREATE TABLE store_provisioning_part2_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    config_json TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    result_code VARCHAR(64),
    error_code VARCHAR(64),
    readiness_evidence_id BIGINT,
    result_json TEXT,
    actor_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT uk_store_part2_request_key UNIQUE (organization_id, store_id, idempotency_key)
);

CREATE INDEX idx_store_part2_request_store
    ON store_provisioning_part2_requests (organization_id, store_id, created_at);

CREATE TABLE store_provisioning_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_code VARCHAR(128) NOT NULL,
    target_id BIGINT NOT NULL,
    request_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_store_part2_resource_identity UNIQUE (store_id, resource_type, resource_code)
);

CREATE INDEX idx_store_part2_resource_request
    ON store_provisioning_resources (request_id, resource_type);

CREATE TABLE store_logical_printer_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    role_code VARCHAR(96) NOT NULL,
    module_code VARCHAR(96) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    mode VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL,
    required BOOLEAN NOT NULL,
    physical_binding_status VARCHAR(32) NOT NULL,
    assigned_printer_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_store_logical_printer_role UNIQUE (store_id, role_code),
    CONSTRAINT uk_store_logical_printer_module UNIQUE (store_id, module_code)
);

CREATE INDEX idx_store_logical_printer_scope
    ON store_logical_printer_roles (organization_id, store_id, enabled);

CREATE TABLE store_device_readiness (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    contract_version VARCHAR(32) NOT NULL,
    trusted_build BOOLEAN NOT NULL,
    worker_status VARCHAR(32) NOT NULL,
    proof_status VARCHAR(32) NOT NULL,
    last_heartbeat_at TIMESTAMP,
    checked_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    evidence_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_store_device_readiness_device UNIQUE (device_id)
);

CREATE INDEX idx_store_device_readiness_scope
    ON store_device_readiness (organization_id, store_id, proof_status, expires_at);

CREATE TABLE store_activation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    expected_readiness_fingerprint CHAR(64),
    status VARCHAR(32) NOT NULL,
    target_state VARCHAR(32),
    readiness_evidence_id BIGINT,
    result_code VARCHAR(64),
    error_code VARCHAR(64),
    result_json TEXT,
    actor_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT uk_store_activation_request_key UNIQUE (organization_id, store_id, idempotency_key)
);

CREATE INDEX idx_store_activation_request_store
    ON store_activation_requests (organization_id, store_id, created_at);
