-- V24__harden_phase_b_part2_evidence_and_device_heartbeat
-- Additive only: immutable readiness evidence history and an explicit device
-- heartbeat marker. No credential, endpoint, hardware or Production data.

CREATE TABLE store_readiness_evidence_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    readiness_fingerprint CHAR(64) NOT NULL,
    evidence_json TEXT NOT NULL,
    checked_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_store_readiness_evidence_history_scope
    ON store_readiness_evidence_history (organization_id, store_id, created_at);

ALTER TABLE store_devices
    ADD COLUMN IF NOT EXISTS last_heartbeat_at TIMESTAMP;
