-- Additive, non-Store-linked ledger for the bounded Staging fixture cleanup
-- path. It preserves request fingerprints and sanitized replay results without
-- creating a reference to any Store that the cleanup path may remove.
CREATE TABLE staging_store_fixture_cleanup_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    store_ids_json TEXT NOT NULL,
    approved_owner_manual_store_ids_json TEXT NOT NULL,
    result_json TEXT,
    actor_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT uq_staging_fixture_cleanup_request_key UNIQUE (organization_id, idempotency_key)
);

CREATE INDEX idx_staging_fixture_cleanup_request_status
    ON staging_store_fixture_cleanup_requests (organization_id, status, created_at);
