-- Additive catalog schema only. Existing option IDs, runtime values and order
-- snapshots are untouched; linking legacy rows is an explicit reconciliation.
CREATE TABLE public.organization_addon_definitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_organization_addon_definitions_code UNIQUE (organization_id, code),
    CONSTRAINT uq_organization_addon_definitions_scope UNIQUE (id, organization_id),
    CONSTRAINT fk_organization_addon_definitions_organization
        FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
    CONSTRAINT chk_organization_addon_definitions_code
        CHECK (code ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$')
);

-- Composite keys protect scope even when a parent row is updated concurrently.
ALTER TABLE public.stores
    ADD CONSTRAINT uq_stores_addon_organization_scope UNIQUE (id, organization_id);
ALTER TABLE public.menu_items
    ADD CONSTRAINT uq_menu_items_addon_store_scope UNIQUE (id, store_id);

CREATE TABLE public.store_addons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id bigint NOT NULL,
    organization_id bigint NOT NULL,
    organization_addon_definition_id bigint NOT NULL,
    name_zh character varying(255) NOT NULL,
    name_en character varying(255),
    price numeric(38, 2) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uq_store_addons_definition UNIQUE (store_id, organization_addon_definition_id),
    CONSTRAINT uq_store_addons_scope UNIQUE (id, store_id),
    CONSTRAINT fk_store_addons_store_organization
        FOREIGN KEY (store_id, organization_id) REFERENCES public.stores(id, organization_id),
    CONSTRAINT fk_store_addons_definition_organization
        FOREIGN KEY (organization_addon_definition_id, organization_id)
        REFERENCES public.organization_addon_definitions(id, organization_id),
    CONSTRAINT chk_store_addons_price CHECK (price >= 0)
);

ALTER TABLE public.menu_item_options ADD COLUMN store_addon_id bigint;
ALTER TABLE public.menu_item_options ADD COLUMN store_addon_store_id bigint;
ALTER TABLE public.menu_item_options ADD COLUMN addon_eligible boolean;
ALTER TABLE public.menu_item_options
    ADD CONSTRAINT fk_menu_item_options_addon_store
        FOREIGN KEY (store_addon_id, store_addon_store_id)
        REFERENCES public.store_addons(id, store_id);
ALTER TABLE public.menu_item_options
    ADD CONSTRAINT fk_menu_item_options_addon_item_store
        FOREIGN KEY (menu_item_id, store_addon_store_id)
        REFERENCES public.menu_items(id, store_id);
ALTER TABLE public.menu_item_options
    ADD CONSTRAINT chk_menu_item_options_addon_link
        CHECK (
            (store_addon_id IS NULL AND store_addon_store_id IS NULL AND addon_eligible IS NULL)
            OR (store_addon_id IS NOT NULL AND store_addon_store_id IS NOT NULL
                AND menu_item_id IS NOT NULL AND addon_eligible IS NOT NULL)
        );
CREATE INDEX idx_menu_item_options_store_addon ON public.menu_item_options (store_addon_id);

-- Organization identity is permanent. Names, price and availability live only
-- on independent Store catalog rows; no business meaning is inferred on update.
CREATE FUNCTION public.enforce_organization_addon_definition_identity()
RETURNS trigger AS $$
BEGIN
    IF NEW.organization_id IS DISTINCT FROM OLD.organization_id
        OR NEW.code IS DISTINCT FROM OLD.code THEN
        RAISE EXCEPTION 'ORGANIZATION_ADDON_DEFINITION_CODE_IMMUTABLE';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_organization_addon_definition_identity
BEFORE UPDATE ON public.organization_addon_definitions
FOR EACH ROW EXECUTE FUNCTION public.enforce_organization_addon_definition_identity();
