CREATE TABLE public.order_submission_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    store_id bigint NOT NULL,
    idempotency_key character varying(255) NOT NULL,
    client_order_id character varying(255) NOT NULL,
    payload_hash character varying(64) NOT NULL,
    order_id bigint,
    status character varying(32) NOT NULL,
    error_code character varying(64),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone
);

ALTER TABLE public.order_submission_requests
    ADD CONSTRAINT uq_order_submission_store_key UNIQUE (store_id, idempotency_key);

CREATE INDEX idx_order_submission_order
    ON public.order_submission_requests (order_id);

CREATE TABLE public.order_dispatch_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    store_id bigint NOT NULL,
    order_id bigint NOT NULL,
    order_update_batch_id bigint,
    module_code character varying(64) NOT NULL,
    event_type character varying(64) NOT NULL,
    source_key character varying(255) NOT NULL,
    status character varying(32) NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone,
    last_error text
);

ALTER TABLE public.order_dispatch_outbox
    ADD CONSTRAINT uq_order_dispatch_source_key UNIQUE (source_key);

CREATE INDEX idx_order_dispatch_due
    ON public.order_dispatch_outbox (status, next_attempt_at, id);

ALTER TABLE public.print_jobs
    ADD COLUMN dispatch_source_key character varying(255);

CREATE UNIQUE INDEX uq_print_jobs_dispatch_source_key
    ON public.print_jobs (dispatch_source_key)
    WHERE dispatch_source_key IS NOT NULL;
