CREATE TABLE public.owner_store_onboarding_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    idempotency_key character varying(255) NOT NULL,
    request_fingerprint character varying(64) NOT NULL,
    status character varying(32) NOT NULL,
    store_id bigint,
    result_code character varying(64),
    error_code character varying(64),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone,
    CONSTRAINT uq_owner_store_onboarding_organization_key UNIQUE (organization_id, idempotency_key)
);

CREATE INDEX idx_owner_store_onboarding_request_store
    ON public.owner_store_onboarding_requests (store_id);
