CREATE TABLE public.staging_synthetic_bootstrap_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id character varying(120) NOT NULL,
    request_fingerprint character varying(64) NOT NULL,
    status character varying(32) NOT NULL,
    runtime_sha character varying(40) NOT NULL,
    tool_sha character varying(40) NOT NULL,
    organization_id bigint,
    source_store_id bigint,
    owner_user_id bigint,
    result_code character varying(64),
    error_code character varying(64),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone,
    CONSTRAINT uq_staging_synthetic_bootstrap_run_id UNIQUE (run_id)
);

CREATE INDEX idx_staging_synthetic_bootstrap_organization
    ON public.staging_synthetic_bootstrap_requests (organization_id);

CREATE INDEX idx_staging_synthetic_bootstrap_source_store
    ON public.staging_synthetic_bootstrap_requests (source_store_id);
